name: flutter_dropzone_example
description: Demonstrates how to use the flutter_dropzone plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_dropzone: ^2.0.0
  pedantic: ^1.11.0

dev_dependency_overrides:
  flutter_dropzone:
    path: ../flutter_dropzone/
  flutter_dropzone_platform_interface:
    path: ../flutter_dropzone_platform_interface/
  flutter_dropzone_web:
    path: ../flutter_dropzone_web/

flutter:
  uses-material-design: true
